# Generated by Django 4.0.1 on 2022-08-11 20:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, validators=[users.models.age_validation]),
        ),
    ]
