# Generated by Django 4.0.1 on 2022-08-11 20:30

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(1930, 1, 1), validators=[users.models.age_validation]),
        ),
    ]
