# Generated by Django 4.0.1 on 2022-08-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('items', models.ManyToManyField(to='advertisements.Advertisement')),
            ],
            options={
                'verbose_name': 'Выборка',
                'verbose_name_plural': 'Выборки',
            },
        ),
    ]
