# Generated by Django 4.0.1 on 2022-08-11 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимальная длина 5 символов')]),
        ),
    ]
