# Generated by Django 4.0.1 on 2022-08-11 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Минимальная длина поля 10 символов')])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Минимальное значение цены 0')])),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
